table backlog

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

	column backlog
		dataType: int64
		summarizeBy: sum
		sourceColumn: backlog

	measure 'Open appeals reported (backlog)' = SUM ( 'backlog'[backlog] )
		formatString: #,0.00
		displayFolder: Measures
		/// Open appeals reported for the 'One question, four answers' visual.

	partition backlog = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\backlog.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"source", type text},
				        {"backlog", Int64.Type}
				    })
				in
				    Typed
